describe("sentence voice behaviour", function() {
  var sentence_voice;
  var reference;

  beforeEach(function() {
    reference = new Reference();
    sentence_voice = new SentenceVoice(reference, new TaggedWordAnalyser(reference), new WordAnalyser(reference));
  });

  it("should correctly detect the voice in the sample set", function() {
    // expect(sentence_voice.get_voice("Every night the office is vacuumed and dusted by the cleaning crew")).toBe('passive');
    // expect(sentence_voice.get_voice("Sugar cane is raised by some people in Hawaii")).toBe('passive');
    // expect(sentence_voice.get_voice("That piece is really enjoyed by the choir")).toBe('passive');
    // expect(sentence_voice.get_voice("The Grand Canyon is viewed by thousands of tourists every year")).toBe('passive');
    // expect(sentence_voice.get_voice("The savannah is roamed by beautiful giraffes")).toBe('passive');
    // expect(sentence_voice.get_voice("There is a considerable range of expertise demonstrated by the spam senders")).toBe('passive');
    // expect(sentence_voice.get_voice("The staff is required to watch a safety video every year")).toBe('likely-active');
    // expect(sentence_voice.get_voice("A movie is going to be watched by us tonight")).toBe('passive');
    // expect(sentence_voice.get_voice("A safety video will be watched by the staff every year")).toBe('passive');
    // expect(sentence_voice.get_voice("A scathing review was written by the critic")).toBe('passive');
    // expect(sentence_voice.get_voice("Alex posted the video on Facebook")).toBe('active');
    // expect(sentence_voice.get_voice("All men are created equal")).toBe('passive');
    // expect(sentence_voice.get_voice("All the reservations will be made by the wedding planner")).toBe('passive');
    // expect(sentence_voice.get_voice("At dinner, six shrimp were eaten by Harry")).toBe('passive');
    // expect(sentence_voice.get_voice("Beautiful giraffes roam the savannah")).toBe('active');
    // expect(sentence_voice.get_voice("By whom were you taught to ski")).toBe('passive');
    // expect(sentence_voice.get_voice("For the bake sale, two dozen cookies will be baked by Susan")).toBe('likely-passive');
    // expect(sentence_voice.get_voice("Groups help participants realize that most of their problems and secrets are shared by others in the group")).toBe('passive');
    // expect(sentence_voice.get_voice("Harry ate six shrimp at dinner")).toBe('active');
    // expect(sentence_voice.get_voice("I ran the obstacle course in record time")).toBe('active');
    // expect(sentence_voice.get_voice("I will clean the house every Saturday")).toBe('active');
    // expect(sentence_voice.get_voice("In this way, the old religion was able to survive the onslaught of new ideas until the old gods were finally displaced by Christianity")).toBe('passive');
    // expect(sentence_voice.get_voice("Instructions will be given to you by the director")).toBe('passive');
    // expect(sentence_voice.get_voice("It was determined by the committee that the report was inconclusive")).toBe('passive');
    // expect(sentence_voice.get_voice("Larry generously donated money to the homeless shelter")).toBe('active');
    // expect(sentence_voice.get_voice("Minor keys, modal movement, and arpeggios are shared by both musical traditions")).toBe('passive');
    // expect(sentence_voice.get_voice("Mom read the novel in one day")).toBe('active');
    // expect(sentence_voice.get_voice("Money was generously donated to the homeless shelter by Larry")).toBe('passive');
    // expect(sentence_voice.get_voice("My sales ad was not responded to by anyone")).toBe('passive');
    // expect(sentence_voice.get_voice("No one responded to my sales ad")).toBe('active');
    // expect(sentence_voice.get_voice("She faxed her application for a new job")).toBe('active');
    // expect(sentence_voice.get_voice("Some people raise sugar cane in Hawaii")).toBe('active');
    // expect(sentence_voice.get_voice("Sue changed the flat tire")).toBe('active');
    // expect(sentence_voice.get_voice("Susan will bake two dozen cupcakes for the bake sale")).toBe('active');
    // expect(sentence_voice.get_voice("The application for a new job was faxed by her")).toBe('passive');
    // expect(sentence_voice.get_voice("The baby was carried by the kangaroo in her pouch")).toBe('passive');
    // expect(sentence_voice.get_voice("The choir really enjoys that piece")).toBe('active');
    // expect(sentence_voice.get_voice("The cleaning crew vacuums and dusts the office every night")).toBe('active');
    // expect(sentence_voice.get_voice("The comet was viewed by the science class")).toBe('passive');
    // expect(sentence_voice.get_voice("The crew paved the entire stretch of highway")).toBe('active');
    // expect(sentence_voice.get_voice("The critic wrote a scathing review")).toBe('active');
    // expect(sentence_voice.get_voice("The director will give you instructions")).toBe('active');
    // expect(sentence_voice.get_voice("The entire house was planted by Tom")).toBe('passive');
    // expect(sentence_voice.get_voice("The entire stretch of highway was paved by the crew")).toBe('passive');
    // expect(sentence_voice.get_voice("The flat tire was changed by Sue")).toBe('passive');
    // expect(sentence_voice.get_voice("The forest fire destroyed the whole suburb")).toBe('active');
    // expect(sentence_voice.get_voice("The homeowners remodeled the house to help it sell")).toBe('active');
    // expect(sentence_voice.get_voice("The house was remodeled by the homeowners to help it sell")).toBe('passive');
    // expect(sentence_voice.get_voice("The house will be cleaned by me every Saturday")).toBe('passive');
    // expect(sentence_voice.get_voice("The kangaroo carried her baby in her pouch")).toBe('active');
    // expect(sentence_voice.get_voice("The last cookie was eaten by whom")).toBe('passive');
    // expect(sentence_voice.get_voice("The metal beams were eventually corroded by the saltwater")).toBe('passive');
    // expect(sentence_voice.get_voice("The money was donated to the school")).toBe('passive');
    // expect(sentence_voice.get_voice("The novel was read by Mom in one day")).toBe('passive');
    // expect(sentence_voice.get_voice("The obstacle course was run by me in record time")).toBe('passive');
    // expect(sentence_voice.get_voice("The paper was marked by Mr. Tan")).toBe('passive');
    // expect(sentence_voice.get_voice("The paper was marked")).toBe('passive');
    // expect(sentence_voice.get_voice("The proposed initiative will be bitterly opposed by abortion rights groups")).toBe('passive');
    // expect(sentence_voice.get_voice("The saltwater eventually corroded the metal beams")).toBe('active');
    // expect(sentence_voice.get_voice("The science class viewed the comet")).toBe('active');
    // expect(sentence_voice.get_voice("The students' questions are always answered by the teacher")).toBe('passive');
    // expect(sentence_voice.get_voice("The teacher always answers the students’ questions")).toBe('active');
    // expect(sentence_voice.get_voice("The team will celebrate their victory tomorrow")).toBe('active');
    // expect(sentence_voice.get_voice("The treaty is being signed by the two kings")).toBe('passive');
    // expect(sentence_voice.get_voice("The two kings are signing the treaty")).toBe('active');
    // expect(sentence_voice.get_voice("The vase got broken during the fight")).toBe('passive');
    // expect(sentence_voice.get_voice("The victory will be celebrated by the team tomorrow")).toBe('passive');
    // expect(sentence_voice.get_voice("The video was posted on Facebook by Alex")).toBe('passive');
    // expect(sentence_voice.get_voice("The wedding planner is making all the reservations")).toBe('active');
    // expect(sentence_voice.get_voice("The whole suburb was destroyed by the forest fire")).toBe('passive');
    // expect(sentence_voice.get_voice("Thousands of tourists view the Grand Canyon every year")).toBe('active');
    // expect(sentence_voice.get_voice("Tim was operated on yesterday")).toBe('passive');
    // expect(sentence_voice.get_voice("Tom painted the entire house")).toBe('active');
    // expect(sentence_voice.get_voice("We are going to watch a movie tonight")).toBe('active');
    // expect(sentence_voice.get_voice("We were given tickets")).toBe('passive');
    // expect(sentence_voice.get_voice("We were invited by our neighbors to attend their party")).toBe('passive');
    // expect(sentence_voice.get_voice("Who ate the last cookie")).toBe('active');
    // expect(sentence_voice.get_voice("Who taught you to ski")).toBe('active');
    // expect(sentence_voice.get_voice("Anita was driven to the theatre.")).toBe('passive');
    // expect(sentence_voice.get_voice("Nowadays, kites are protected.")).toBe('passive');
    // expect(sentence_voice.get_voice("The olives are stoned and crushed in this area.")).toBe('passive');
    // expect(sentence_voice.get_voice("Anita was driven to the theatre by Carla.")).toBe('passive');
    // expect(sentence_voice.get_voice("Nowadays, kites are protected by law.")).toBe('passive');
    // expect(sentence_voice.get_voice("The olives are stoned and crushed in this area by my son.")).toBe('passive');
    // expect(sentence_voice.get_voice("Russell will be identified by the local postman")).toBe('passive');
    // expect(sentence_voice.get_voice("The local postman will identify Russell")).toBe('active');
    // expect(sentence_voice.get_voice("The document had been released into the public domain")).toBe('passive');
    // expect(sentence_voice.get_voice("Jackie released the document into the public domain.")).toBe('active');
    // expect(sentence_voice.get_voice("Bad advice was given.")).toBe('passive');
    // expect(sentence_voice.get_voice("A serious failing in standing operating procedures had occurred.")).toBe('passive');
    // expect(sentence_voice.get_voice("Pistachio nuts are grown in Iran.")).toBe('passive');
    // expect(sentence_voice.get_voice("His parade uniform was stolen.")).toBe('passive');
    // expect(sentence_voice.get_voice("English and German are spoken in many Cornish campsites.")).toBe('passive');
    // expect(sentence_voice.get_voice("The windows must be secured.")).toBe('passive');
    // expect(sentence_voice.get_voice("Divorces are made in heaven.")).toBe('passive');
    // expect(sentence_voice.get_voice("An estimated 258,000 people were injured in alcohol-related crashes.")).toBe('passive');
    // expect(sentence_voice.get_voice("Martin crashed into the barrier and was tossed in the crowd.")).toBe('passive');
    // expect(sentence_voice.get_voice("Once a week, Tom cleans the house.")).toBe('active');
    // expect(sentence_voice.get_voice("Once a week, the house is cleaned by Tom.")).toBe('passive');
    // expect(sentence_voice.get_voice("Right now, Sarah is writing the letter.")).toBe('active');
    // expect(sentence_voice.get_voice("Right now, the letter is being written by Sarah.")).toBe('passive');
    // expect(sentence_voice.get_voice("Sam repaired the car.")).toBe('active');
    // expect(sentence_voice.get_voice("The car was repaired by Sam.")).toBe('passive');
    expect(sentence_voice.get_voice("The salesman was helping the customer when the thief came into the store.")).toBe('active');
    // expect(sentence_voice.get_voice("The customer was being helped by the salesman when the thief came into the store.")).toBe('passive');
    // expect(sentence_voice.get_voice("Many tourists have visited that castle.")).toBe('active');
    // expect(sentence_voice.get_voice("That castle has been visited by many tourists.")).toBe('passive');
    expect(sentence_voice.get_voice("Recently, John has been doing the work.")).toBe('active');
    // expect(sentence_voice.get_voice("Recently, the work has been being done by John.")).toBe('passive');
    expect(sentence_voice.get_voice("George had repaired many cars before he received his mechanic's license.")).toBe('active');
    // expect(sentence_voice.get_voice("A beautiful dinner is going to be made by Sally tonight.")).toBe('passive');
    // expect(sentence_voice.get_voice("At 8:00 PM tonight, John is going to be washing the dishes.")).toBe('active');
    expect(sentence_voice.get_voice("At 8:00 PM tonight, John will be washing the dishes.")).toBe('active');
    // expect(sentence_voice.get_voice("At 8:00 PM tonight, the dishes are going to be being washed by John.")).toBe('passive');
    // expect(sentence_voice.get_voice("At 8:00 PM tonight, the dishes will be being washed by John.")).toBe('passive');
    expect(sentence_voice.get_voice("Chef Jones had been preparing the restaurant's fantastic dinners for two years before he moved to Paris.")).toBe('active');
    expect(sentence_voice.get_voice("I knew John would finish the work by 5:00 PM.")).toBe('active');
    // expect(sentence_voice.get_voice("I knew the work would be finished by 5:00 PM.")).toBe('passive');
    // expect(sentence_voice.get_voice("I thought a beautiful dinner was going to be made by Sally tonight.")).toBe('passive');
    expect(sentence_voice.get_voice("I thought Sally was going to make a beautiful dinner tonight.")).toBe('active');
    // expect(sentence_voice.get_voice("Jerry used to pay the bills.")).toBe('active');
    // expect(sentence_voice.get_voice("Many cars had been repaired by George before he received his mechanic's license.")).toBe('passive');
    // expect(sentence_voice.get_voice("My mother would always make the pies.")).toBe('active');
    // expect(sentence_voice.get_voice("Sally is going to make a beautiful dinner tonight.")).toBe('active');
    // expect(sentence_voice.get_voice("Someone will finish the work by 5:00 PM.")).toBe('active');
    // expect(sentence_voice.get_voice("The bills used to be paid by Jerry.")).toBe('passive');
    expect(sentence_voice.get_voice("The famous artist is going to have been painting the mural for over six months by the time it is finished.")).toBe('active');
    expect(sentence_voice.get_voice("The famous artist will have been painting the mural for over six months by the time it is finished.")).toBe('active');
    // expect(sentence_voice.get_voice("The mural is going to have been being painted by the famous artist for over six months by the time it is finished.")).toBe('passive');
    // expect(sentence_voice.get_voice("The mural will have been being painted by the famous artist for over six months by the time it is finished.")).toBe('passive');
    // expect(sentence_voice.get_voice("The pies would always be made by my mother.")).toBe('passive');
    expect(sentence_voice.get_voice("The project is going to have been completed before the deadline.")).toBe('passive');
    // expect(sentence_voice.get_voice("The project will have been completed before the deadline.")).toBe('passive');
    // expect(sentence_voice.get_voice("The restaurant's fantastic dinners had been being prepared by Chef Jones for two years before he moved to Paris.")).toBe('passive');
    // expect(sentence_voice.get_voice("The work will be finished by 5:00 PM.")).toBe('passive');
    expect(sentence_voice.get_voice("They are going to have completed the project before the deadline.")).toBe('active');
    expect(sentence_voice.get_voice("They will have completed the project before the deadline.")).toBe('active');
  });
});