describe("sentence voice behaviour", function() {
  var sentence_voice;
  var reference;

  beforeEach(function() {
    reference = new Reference();
    sentence_voice = new SentenceVoice(reference, new TaggedWordAnalyser(reference), new WordAnalyser(reference));
  });

  it("should correctly detect the voice in the sample set", function() {
    expect(sentence_voice.get_voice("Every night the office is vacuumed and dusted by the cleaning crew")).toBe('passive');
    expect(sentence_voice.get_voice("Sugar cane is raised by some people in Hawaii")).toBe('passive');
    expect(sentence_voice.get_voice("That piece is really enjoyed by the choir")).toBe('passive');
    expect(sentence_voice.get_voice("The Grand Canyon is viewed by thousands of tourists every year")).toBe('passive');
    expect(sentence_voice.get_voice("The savannah is roamed by beautiful giraffes")).toBe('passive');
    expect(sentence_voice.get_voice("There is a considerable range of expertise demonstrated by the spam senders")).toBe('passive');
    expect(sentence_voice.get_voice("The staff is required to watch a safety video every year")).toBe('active');
    expect(sentence_voice.get_voice("A movie is going to be watched by us tonight")).toBe('passive');
    expect(sentence_voice.get_voice("A safety video will be watched by the staff every year")).toBe('passive');
    expect(sentence_voice.get_voice("A scathing review was written by the critic")).toBe('passive');
    expect(sentence_voice.get_voice("Alex posted the video on Facebook")).toBe('active');
    expect(sentence_voice.get_voice("All men are created equal")).toBe('passive');
    expect(sentence_voice.get_voice("All the reservations will be made by the wedding planner")).toBe('passive');
    expect(sentence_voice.get_voice("At dinner, six shrimp were eaten by Harry")).toBe('passive');
    expect(sentence_voice.get_voice("Beautiful giraffes roam the savannah")).toBe('active');
    expect(sentence_voice.get_voice("By whom were you taught to ski")).toBe('passive');
    expect(sentence_voice.get_voice("For the bake sale, two dozen cookies will be baked by Susan")).toBe('likely-passive');
    expect(sentence_voice.get_voice("Groups help participants realize that most of their problems and secrets are shared by others in the group")).toBe('passive');
    expect(sentence_voice.get_voice("Harry ate six shrimp at dinner")).toBe('active');
    expect(sentence_voice.get_voice("I ran the obstacle course in record time")).toBe('active');
    expect(sentence_voice.get_voice("I will clean the house every Saturday")).toBe('active');
    expect(sentence_voice.get_voice("In this way, the old religion was able to survive the onslaught of new ideas until the old gods were finally displaced by Christianity")).toBe('passive');
    expect(sentence_voice.get_voice("Instructions will be given to you by the director")).toBe('passive');
    expect(sentence_voice.get_voice("It was determined by the committee that the report was inconclusive")).toBe('passive');
    expect(sentence_voice.get_voice("Larry generously donated money to the homeless shelter")).toBe('active');
    expect(sentence_voice.get_voice("Minor keys, modal movement, and arpeggios are shared by both musical traditions")).toBe('passive');
    expect(sentence_voice.get_voice("Mom read the novel in one day")).toBe('active');
    expect(sentence_voice.get_voice("Money was generously donated to the homeless shelter by Larry")).toBe('passive');
    expect(sentence_voice.get_voice("My sales ad was not responded to by anyone")).toBe('passive');
    expect(sentence_voice.get_voice("No one responded to my sales ad")).toBe('active');
    expect(sentence_voice.get_voice("She faxed her application for a new job")).toBe('active');
    expect(sentence_voice.get_voice("Some people raise sugar cane in Hawaii")).toBe('active');
    expect(sentence_voice.get_voice("Sue changed the flat tire")).toBe('active');
    expect(sentence_voice.get_voice("Susan will bake two dozen cupcakes for the bake sale")).toBe('active');
    expect(sentence_voice.get_voice("The application for a new job was faxed by her")).toBe('passive');
    expect(sentence_voice.get_voice("The baby was carried by the kangaroo in her pouch")).toBe('passive');
    expect(sentence_voice.get_voice("The choir really enjoys that piece")).toBe('active');
    expect(sentence_voice.get_voice("The cleaning crew vacuums and dusts the office every night")).toBe('active');
    expect(sentence_voice.get_voice("The comet was viewed by the science class")).toBe('passive');
    expect(sentence_voice.get_voice("The crew paved the entire stretch of highway")).toBe('active');
    expect(sentence_voice.get_voice("The critic wrote a scathing review")).toBe('active');
    expect(sentence_voice.get_voice("The director will give you instructions")).toBe('active');
    expect(sentence_voice.get_voice("The entire house was planted by Tom")).toBe('passive');
    expect(sentence_voice.get_voice("The entire stretch of highway was paved by the crew")).toBe('passive');
    expect(sentence_voice.get_voice("The flat tire was changed by Sue")).toBe('passive');
    expect(sentence_voice.get_voice("The forest fire destroyed the whole suburb")).toBe('active');
    expect(sentence_voice.get_voice("The homeowners remodeled the house to help it sell")).toBe('active');
    expect(sentence_voice.get_voice("The house was remodeled by the homeowners to help it sell")).toBe('passive');
    expect(sentence_voice.get_voice("The house will be cleaned by me every Saturday")).toBe('passive');
    expect(sentence_voice.get_voice("The kangaroo carried her baby in her pouch")).toBe('active');
    expect(sentence_voice.get_voice("The last cookie was eaten by whom")).toBe('passive');
    expect(sentence_voice.get_voice("The metal beams were eventually corroded by the saltwater")).toBe('passive');
    expect(sentence_voice.get_voice("The money was donated to the school")).toBe('passive');
    expect(sentence_voice.get_voice("The novel was read by Mom in one day")).toBe('passive');
    expect(sentence_voice.get_voice("The obstacle course was run by me in record time")).toBe('passive');
    expect(sentence_voice.get_voice("The paper was marked by Mr. Tan")).toBe('passive');
    expect(sentence_voice.get_voice("The paper was marked")).toBe('passive');
    expect(sentence_voice.get_voice("The proposed initiative will be bitterly opposed by abortion rights groups")).toBe('passive');
    expect(sentence_voice.get_voice("The saltwater eventually corroded the metal beams")).toBe('active');
    expect(sentence_voice.get_voice("The science class viewed the comet")).toBe('active');
    expect(sentence_voice.get_voice("The students' questions are always answered by the teacher")).toBe('passive');
    expect(sentence_voice.get_voice("The teacher always answers the students’ questions")).toBe('active');
    expect(sentence_voice.get_voice("The team will celebrate their victory tomorrow")).toBe('active');
    expect(sentence_voice.get_voice("The treaty is being signed by the two kings")).toBe('passive');
    expect(sentence_voice.get_voice("The two kings are signing the treaty")).toBe('active');
    expect(sentence_voice.get_voice("The vase got broken during the fight")).toBe('passive');
    expect(sentence_voice.get_voice("The victory will be celebrated by the team tomorrow")).toBe('passive');
    expect(sentence_voice.get_voice("The video was posted on Facebook by Alex")).toBe('passive');
    expect(sentence_voice.get_voice("The wedding planner is making all the reservations")).toBe('active');
    expect(sentence_voice.get_voice("The whole suburb was destroyed by the forest fire")).toBe('passive');
    expect(sentence_voice.get_voice("Thousands of tourists view the Grand Canyon every year")).toBe('active');
    expect(sentence_voice.get_voice("Tim was operated on yesterday")).toBe('passive');
    expect(sentence_voice.get_voice("Tom painted the entire house")).toBe('active');
    expect(sentence_voice.get_voice("We are going to watch a movie tonight")).toBe('active');
    expect(sentence_voice.get_voice("We were given tickets")).toBe('passive');
    expect(sentence_voice.get_voice("We were invited by our neighbors to attend their party")).toBe('passive');
    expect(sentence_voice.get_voice("Who ate the last cookie")).toBe('active');
    expect(sentence_voice.get_voice("Who taught you to ski")).toBe('active');
  });
});